<a href="https://colab.research.google.com/github/remy882/ejercicios/blob/main/examen_final_SETIEMBRE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np

# arreglo del 1 al 20
arreglo = np.arange(1, 21)

print("arregl en dimension 1: ",arreglo)



#2. Selecciona los múltiplos de 3 de ese arreglo y muéstralos

multiplos_3 = arreglo[arreglo % 3 == 0]

print("\n Múltiplos de 3:", multiplos_3)


arregl en dimension 1:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 Múltiplos de 3: [ 3  6  9 12 15 18]




3. Genera una matriz aleatoria de tamaño 5x5 con números entre 0 y 1

In [4]:
import numpy as np


# 3. Generar matriz aleatoria de 5x5
matriz = np.random.rand(5, 5)

print("Matriz aleatoria 5x5:")
print(matriz)



# 4. Calcula la media, la desviación estándar y el valor máximo de esa matriz.
media = np.mean(matriz)
desviacion = np.std(matriz)
maximo = np.max(matriz)

print("\n RESULTADOS:")
print("Media:", media)
print("Desviación estándar:", desviacion)
print("Valor máximo:", maximo)


Matriz aleatoria 5x5:
[[0.74878203 0.03303954 0.2472439  0.62371081 0.42668567]
 [0.9493257  0.71827345 0.78745251 0.74636334 0.07387696]
 [0.01476413 0.24429798 0.94727152 0.2008441  0.77162267]
 [0.94764601 0.9966134  0.48483072 0.81726315 0.7704925 ]
 [0.76651764 0.70461258 0.11489138 0.71271887 0.60711371]]

📊 Resultados:
Media: 0.5782501709982824
Desviación estándar: 0.3091297147694535
Valor máximo: 0.9966134048285329


In [37]:
import numpy as np

# Generar matriz aleatoria de 5x5
matriz = np.random.rand(5, 5)



#5. Transforma la matriz en un vector de una sola dimensión
vector = matriz.flatten()

print("\nVector en una sola dimensión:")
print(vector)
print("Tamaño:", vector.size)



Vector en una sola dimensión:
[0.22670299 0.73308234 0.65954712 0.64642755 0.99266571 0.80431935
 0.1796099  0.2073639  0.84882758 0.01954611 0.5710274  0.12124905
 0.17964864 0.99332355 0.11366107 0.0163514  0.01655406 0.9905564
 0.3121632  0.17831377 0.99053577 0.3904667  0.39048864 0.99044677
 0.74399758]
Tamaño: 25


PARTEEEE 2: Fundamentos Pandas

1. Crea un DataFrame con los siguientes datos de estudiantes:

In [38]:
import pandas as pd

# Datos de estudiantes
datos = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}

# Crear DataFrame
df = pd.DataFrame(datos)

print(" DataFrame de Estudiantes:")
print(df)

print("\n")

#2. Calcula el promedio de cada columna numérica.


promedios = df.mean(numeric_only=True).to_frame(name="Promedio:")
print()
print(promedios)

#3. Filtra los estudiantes con nota de IA mayor a 15

print("\n\n📋 Estudiantes con Nota_IA > 15:")
print()
filtro = df[df["Nota_IA"] > 15]
print(filtro)


#4. Agrega una nueva columna llamada Promedio que contenga el promedio de Nota_Matemáticas y Nota_IA.

#Columna nueva con promedio ingresado
df["Promedio"] = (df["Nota_Matemáticas"] + df["Nota_IA"]) / 2
print()
print("\n📋 DataFrame con columna Promedio:")
print()
print(df)

# 5. Ordena el DataFrame según la columna Promedio de mayor a menor.

df_ordenado = df.sort_values(by="Promedio", ascending=False)

print("\n\n 📊 DataFrame ordenado por Promedio (de mayor a menor):")
print()
print(df_ordenado)


 DataFrame de Estudiantes:
  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20



                  Promedio:
Edad                   20.4
Nota_Matemáticas       16.0
Nota_IA                16.4


📋 Estudiantes con Nota_IA > 15:

  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20


📋 DataFrame con columna Promedio:

  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


 📊 DataFrame ordenado por Promedio (de mayor a menor

PARTE 3: Algoritmia aplicada


1. Escribe una función en Python que reciba una lista de números y devuelva:


o   El número mayor


o   El número menor


o   El promedio

In [24]:
def analizar_lista(numeros):
    mayor = max(numeros)
    menor = min(numeros)
    promedio = sum(numeros) / len(numeros)
    return mayor, menor, promedio

# Ejemplo de uso
lista = [10, 5, 20, 7, 15]
mayor, menor, promedio = analizar_lista(lista)

print("Lista:", lista)
print("Mayor:", mayor)
print("Menor:", menor)
print("Promedio:", promedio)



Lista: [10, 5, 20, 7, 15]
Mayor: 20
Menor: 5
Promedio: 11.4


2. Usando NumPy, implementa una función de activación Sigmoide definida como:

f(x)=11+e−xf(x) = \frac{1}{1 + e^{-x}}f(x)=1+e−x1

Aplica la función a un arreglo x = np.array([-2, -1, 0, 1, 2]).

In [25]:
import numpy as np

# Definir función sigmoide
def sigmoide(x):
    return 1 / (1 + np.exp(-x))

# Arreglo de prueba
x = np.array([-2, -1, 0, 1, 2])
resultado = sigmoide(x)

print("x =", x)
print("Sigmoide(x) =", resultado)


x = [-2 -1  0  1  2]
Sigmoide(x) = [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


3. Crea una función que clasifique a los estudiantes del DataFrame en "Aprobado"
si su Promedio ≥ 14, y "Desaprobado" en caso contrario. Añade una nueva
columna llamada Estado.


In [39]:
import pandas as pd

#EJERCICIO que usamos el grafico de la  parte 1
# DataFrame con promedios
datos = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20],
    "Promedio": [17.5, 14.5, 17.0, 12.5, 19.5]
}
df = pd.DataFrame(datos)

# Función para clasificar estudiantes
def clasificar(promedio):
    return "Aprobado" if promedio >= 14 else "Desaprobado"

# Crear columna Estado
df["Estado"] = df["Promedio"].apply(clasificar)

print(" DataFrame final con Estado:")
print(df)

 DataFrame final con Estado:
  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado


PARTE 4: Mini-proyecto

Agrega una nueva columna llamada Crecimiento que calcule el porcentaje de
crecimiento entre Ventas_2024 y Ventas_2025.

In [30]:
import pandas as pd

# Datos
datos = {
    'Producto' : ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}
#mostra columna

df = pd.DataFrame(datos)
# 1. Agregar columna Crecimiento (%) redondeada a 2 decimales
df["Crecimiento"] = (((df["Ventas_2025"] - df["Ventas_2024"]) / df["Ventas_2024"]) * 100).round(2)

print("📊 DataFrame con Crecimiento (%):\n")
print(df)


# 2. Identificar producto con mayor crecimiento
mayor_crecimiento = df.loc[df["Crecimiento"].idxmax()]

print("\n\n🔥 Producto con mayor crecimiento:\n")
print(mayor_crecimiento.to_string(index=True))

📊 DataFrame con Crecimiento (%):

  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200        66.67
1        B          340          400        17.65
2        C          560          600         7.14
3        D          230          300        30.43
4        E          150          180        20.00


🔥 Producto con mayor crecimiento:

Producto           A
Ventas_2024      120
Ventas_2025      200
Crecimiento    66.67


PARTEEE 5: Resolución de ecuaciones



1. Ecuación de primer grado

-Implementa una función en Python que resuelva una ecuación de la forma:

   ax+b=0ax + b = 0ax+b=0

   por ejemplo: 2x + 4 = 0.

-La función debe retornar el valor de x.

In [31]:
def resolver_ecuacion(a, b):
    if a == 0:
        if b == 0:
            return "La ecuación tiene infinitas soluciones."
        else:
            return "La ecuación no tiene solución."
    else:
        x = -b / a
        return x

# Ejemplo: 2x + 4 = 0
resultado = resolver_ecuacion(2, 4)
print("El valor de x es:", resultado)


El valor de x es: -2.0


2. Ecuación de segundo grado

 Implementa una función en Python que resuelva una ecuación de la forma:

ax2+bx+c=0ax^2 + bx + c = 0ax2+bx+c=0


usando la fórmula general:

x=−b±b2−4ac2ax = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}x=2a−b±b2−4ac


 La función debe retornar las dos soluciones (reales o complejas)

In [32]:
import cmath  # Para raíces cuadradas de numeros negativos

def resolver_ecuacion_segundo_grado(a, b, c):
    if a == 0:
        return "No es una ecuación de segundo grado (a = 0)."

    discriminante = b**2 - 4*a*c
    raiz_discriminante = cmath.sqrt(discriminante)

    x1 = (-b + raiz_discriminante) / (2*a)
    x2 = (-b - raiz_discriminante) / (2*a)

    return x1, x2

# Ejemplo: x^2 - 5x + 6 = 0
resultado = resolver_ecuacion_segundo_grado(1, -5, 6)
print("Las soluciones son:", resultado)


Las soluciones son: ((3+0j), (2+0j))
